## Numpy array and basics
Learning Numpy with chai aur code

In [1]:
import numpy as np    # import NumPy library with alias 'np'

### Creating array from list

In [3]:
arr_1d = np.array([1, 2, 3, 4, 5])
# np.array() → converts Python list into NumPy array
# [1,2,3,4,5] → 1D data (single row)

print("1D array : ", arr_1d)


arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
# outer [] → contains rows
# inner [] → each row
# total → 2 rows, 3 columns

print("2D array : ", arr_2d)

1D array :  [1 2 3 4 5]
2D array :  [[1 2 3]
 [4 5 6]]


### List vs Numpy array

In [ ]:
py_list = [1, 2, 3]
print("Python list multiplication : ", py_list * 2)

np_array = np.array([1, 2, 3])      #element wise multiplication
print("Python array multiplication : ", np_array * 2)


import time     # used to measure execution time
start = time.time()
py_list = [i*2 for i in range(1000000)]
# list comprehension (loop internally)
print("\n List operation time : ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
# vectorized operation (no explicit loop)
print("\n Numpy operation time : ", time.time() - start)

Python list multiplication :  [1, 2, 3, 1, 2, 3]
Python array multiplication :  [2 4 6]

 List operation time :  0.052591562271118164

 Numpy operation time :  0.004000663757324219


## Creating array from scratch

In [ ]:
zeros = np.zeros((3, 4))
# creates array of shape (3 rows, 4 columns) filled with 0
print("Zeros array: \n", zeros)

ones = np.ones((2, 3))
# creates array of shape (2 rows, 3 columns) filled with 1
print("\n Ones array: \n", ones)

full = np.full((2, 2), 7)
# creates array of shape (2x2) filled with value 7
print("\n Full array: \n", full)

random = np.random.random((2, 3))
# creates array of shape (2x3) with random values between 0 and 1
print("\n Random array: \n", random)

sequence = np.arange(0, 10, 2)
# start=0, stop=10 (exclusive), step=2 → [0,2,4,6,8]
print("\n Sequence array: \n", sequence)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]

 Full array: 
 [[7 7]
 [7 7]]

 Random array: 
 [[0.62779085 0.55519428 0.15762802]
 [0.80964013 0.64404442 0.66450454]]

 Sequence array: 
 [0 2 4 6 8]


## Vector, Matrix and Tensor

In [ ]:
vector = np.array([1, 2, 3])
# 1D array → single dimension
# shape → (3,)
print("Vector : ", vector)


matrix = np.array([[1, 2, 3], [4, 5, 6]])
# 2D array → rows and columns
# shape → (2, 3)
print("\n Matrix : ", matrix)


tensor = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
# 3D array → multiple matrices stacked
# shape → (2, 2, 2)
print("\n Tensor : ", tensor)

Vector :  [1 2 3]

 Matrix :  [[1 2 3]
 [4 5 6]]

 Tensor :  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Array properties

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
# 2D array → 2 rows, 3 columns

print("Shape ", arr.shape)
# shape → (rows, columns) → (2, 3)

print("Dimension ", arr.ndim)
# ndim → number of dimensions → 2

print("Size ", arr.size)
# size → total number of elements → 6

print("Dtype ", arr.dtype)
# dtype → data type of elements → int32 / int64 (depends on system)

Shape  (2, 3)
Dimension  2
Size  6
Dtype  int64


## Array Reshaping

In [ ]:
arr = np.arange(12)
# creates array → [0,1,2,...,11]
print("Original Array : ", arr)

reshaped = arr.reshape((3, 4))
# convert into 3 rows, 4 columns
# total elements must match (3*4 = 12)
print("\n Reshaped Array : ", reshaped)

flattened = reshaped.flatten()
# returns new copy (changes won't affect original)
print("\n Flattened Array : ", flattened)

#ravel (returns view, instead of copy)
raveled = reshaped.ravel()
# returns view (linked to original array)
print("\n Raveled Array : ", raveled)

#Transpose
transpose = reshaped.T
# shape (3,4) → (4,3)
print("\n Transposed Array : ", transpose)

Original Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped Array :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed Array :  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
