## Numpy array and basics
Learning Numpy with chai aur code

In [2]:
import numpy as np

### Creating array from list

In [5]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array : ", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array : ", arr_2d)

1D array :  [1 2 3 4 5]
2D array :  [[1 2 3]
 [4 5 6]]


### List vs Numpy array

In [8]:
py_list = [1, 2, 3]
print("Python list multiplication : ", py_list * 2)

np_array = np.array([1, 2, 3])      #element wise multiplication
print("Python array multiplication : ", np_array * 2)


import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time : ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time : ", time.time() - start)

Python list multiplication :  [1, 2, 3, 1, 2, 3]
Python array multiplication :  [2 4 6]

 List operation time :  0.052591562271118164

 Numpy operation time :  0.004000663757324219


## Creating array from scratch

In [15]:
zeros = np.zeros((3, 4))
print("Zeros array: \n", zeros)

ones = np.ones((2, 3))
print("Ones array: \n", ones)

full = np.full((2, 2), 7)
print("Full array: \n", full)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array: 
 [[7 7]
 [7 7]]
