## Numpy Array Operations

In [2]:
import numpy as np

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing : ", arr[2:7])
print("With Step : ", arr[1:8:2])
print("Negative indexing : ", arr[-3])

Basic Slicing :  [3 4 5 6 7]
With Step :  [2 4 6 8]
Negative indexing :  8


In [7]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific Element : ", arr_2d[1, 2])
print("Entire Row : ", arr_2d[1])
print("Entire Column : ", arr_2d[:, 1])

Specific Element :  6
Entire Row :  [4 5 6]
Entire Column :  [2 5 8]


## Sorting

In [10]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array : ", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array by column : ", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2D array by row : ", np.sort(arr_2d_unsorted, axis=1))

Sorted Array :  [1 1 2 3 4 5 6 9]
Sorted 2D array by column :  [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by row :  [[1 3]
 [1 2]
 [2 3]]


## Filtering

In [14]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_numbers = numbers[numbers % 2 == 0]
print("Even numbers are : ", even_numbers)

Even numbers are :  [ 2  4  6  8 10]


## Filter with Mask

In [16]:
mask = numbers > 5
print("Numbers greater than 5 are : ", numbers[mask])

Numbers greater than 5 are :  [ 6  7  8  9 10]


## Fancy Indexing vs np.where()

In [19]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP Where : ", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP Where :  [ 6  7  8  9 10]


In [20]:
condition_array = np.where(numbers > 5, numbers * 4, numbers)
print(condition_array)

[ 1  2  3  4  5 24 28 32 36 40]


## Adding and Removing data

In [23]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = arr1 + arr2
print(combined)

combined = np.concatenate((arr1, arr2))
print(combined)

[5 7 9]
[1 2 3 4 5 6]


## Array Compatibility

In [24]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

print("Compatibility Shapes : ", a.shape == b.shape)

Compatibility Shapes :  False


In [27]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))
print("Original Array : ", original)
print("With new row : ", with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("With new column : ", with_new_col)

Original Array :  [[1 2]
 [3 4]]
With new row :  [[1 2]
 [3 4]
 [5 6]]
With new column :  [[1 2 7]
 [3 4 8]]


In [29]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
print("Array after deletion : ", deleted)

Array after deletion :  [1 2 4 5]
