## Numpy Array Operations

In [2]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# 1D array → index starts from 0

print("Basic Slicing : ", arr[2:7])
# start=2, stop=7 (exclusive)
# output → [3 4 5 6 7]

print("With Step : ", arr[1:8:2])
# start=1, stop=8, step=2
# output → [2 4 6 8]

print("Negative indexing : ", arr[-3])
# -1 → last element
# -3 → third element from end → 8

Basic Slicing :  [3 4 5 6 7]
With Step :  [2 4 6 8]
Negative indexing :  8


In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# 3x3 matrix → shape (3,3)

# Access specific element
print("Specific Element : ", arr_2d[1, 2])
# row=1, col=2 → value = 6

# Access entire row
print("Entire Row : ", arr_2d[1])
# row index 1 → [4 5 6]

# Access entire column
print("Entire Column : ", arr_2d[:, 1])
# : → all rows
# col=1 → [2 5 8]

Specific Element :  6
Entire Row :  [4 5 6]
Entire Column :  [2 5 8]


## Sorting

In [ ]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])

print("Sorted Array : ", np.sort(unsorted))
# sorts in ascending order
# output → [1 1 2 3 4 5 6 9]

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])

# Sort by column (axis=0)
print("Sorted 2D array by column : ", np.sort(arr_2d_unsorted, axis=0))
# sorts each column independently (top → bottom)

# Sort by row (axis=1)
print("Sorted 2D array by row : ", np.sort(arr_2d_unsorted, axis=1))
# sorts each row independently (left → right)

Sorted Array :  [1 1 2 3 4 5 6 9]
Sorted 2D array by column :  [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by row :  [[1 3]
 [1 2]
 [2 3]]


## Filtering

In [ ]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

even_numbers = numbers[numbers % 2 == 0]
# numbers % 2 == 0 → creates boolean array (True/False)
# True → element selected
# False → element ignored

print("Even numbers are : ", even_numbers)
# output → [2 4 6 8 10]

Even numbers are :  [ 2  4  6  8 10]


## Filter with Mask

In [ ]:
mask = numbers > 5
# condition applied → returns boolean array
# example → [False False False False False True True True True True]

print("Numbers greater than 5 are : ", numbers[mask])
# selects elements where mask is True → [6 7 8 9 10]

Numbers greater than 5 are :  [ 6  7  8  9 10]


## Fancy Indexing vs np.where()

In [ ]:
indices = [0, 2, 4]
print(numbers[indices])
# selects elements at given indices
# output → [1 3 5]

where_result = np.where(numbers > 5)
# returns indices where condition is True
# output → (array([5,6,7,8,9]),)

print(where_result)

print("NP Where : ", numbers[where_result])
# use indices to get values → [6 7 8 9 10]

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP Where :  [ 6  7  8  9 10]


In [ ]:
condition_array = np.where(numbers > 5, numbers * 4, numbers)
# condition → numbers > 5
# if True  → numbers * 4
# if False → original number

print(condition_array)

[ 1  2  3  4  5 24 28 32 36 40]


## Adding and Removing data

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise addition
combined = arr1 + arr2
# adds corresponding elements → [1+4, 2+5, 3+6]
print(combined)

# Concatenation (joining arrays)
combined = np.concatenate((arr1, arr2))
# joins arrays end-to-end → [1 2 3 4 5 6]
print(combined)

[5 7 9]
[1 2 3 4 5 6]


## Array Compatibility

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

# Shape compatibility check
print("Compatibility Shapes : ", a.shape == b.shape)
# compares shapes of arrays
# a.shape → (3,)
# b.shape → (4,)
# output → False (not compatible)

Compatibility Shapes :  False


In [ ]:
original = np.array([[1, 2], [3, 4]])
# shape → (2,2)

# Add new row (vertical stacking)
new_row = np.array([[5, 6]])
# shape → (1,2) → must match columns

with_new_row = np.vstack((original, new_row))
# stacks row-wise → adds at bottom
print("Original Array : ", original)
print("With new row : ", with_new_row)
# result → (3,2)

# Add new column (horizontal stacking)
new_col = np.array([[7], [8]])
# shape → (2,1) → must match rows

with_new_col = np.hstack((original, new_col))
# stacks column-wise → adds at right
print("With new column : ", with_new_col)
# result → (2,3)

Original Array :  [[1 2]
 [3 4]]
With new row :  [[1 2]
 [3 4]
 [5 6]]
With new column :  [[1 2 7]
 [3 4 8]]


In [3]:
arr = np.array([1, 2, 3, 4, 5])

# Delete element at index 2
deleted = np.delete(arr, 2)
# removes element at index 2 (value = 3)

print("Array after deletion : ", deleted)

Array after deletion :  [1 2 4 5]
